### ISSUE TITLE
Unable to extract JS player URL

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/alltube_ynh#13]
**Describe the bug**
*A clear and concise description of what the bug is.*
`ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.` I asked to the upstream repository, i told me to update, so i think i have no choice but wait until you update the current repo.
**Versions**
- Hardware: Desktop PC
- YunoHost version: 4.0.8.2
- I have access to my server: full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no 
- Using, or trying to install package version/branch: master

**To Reproduce**
   1. Go to the main page
   2. Paste a video URL
   3. Click on download

**Expected behavior**
Video download.

**Comment by plopoyop** [comment]
Alltube includes youtube-dl in it's installation.
This yunohost package already includes last alltube stable release.
So we must wait for the 3.0 release.

**Comment by stemy2** [comment]
> Alltube includes youtube-dl in it's installation.
> This yunohost package already includes last alltube stable release.
> So we must wait for the 3.0 release.

So how do you explain that a same video have a such bug on my instance but not on the official instance ?

**Comment by plopoyop** [comment]
No idea, the version is not displayed but it looks like it is not the last stable on the demo.
