### ISSUE TITLE
Serious security issue with bookmarklet link

### ISSUE THREAD

**Issue by Zornell** [YunoHost-Apps/alltube_ynh#31]
Hi there,
so i just installed alltube in a fresh yunohost (version 4.3.6.3) install and i noticed that my username and password are included in the bookmarklet link:

```
[...]
<div id="bookmarklet" class="bookmarklet_wrapper">
        <p> Drag this to your bookmarks bar: </p>
        <a class="bookmarklet small-font"
           href="javascript:window.location='https://[USERNAME]:[PASSWORD]@example.com/alltube/info?url=%25url%25'.replace('%url%', encodeURIComponent(location.href));">Bookmarklet</a>
    </div>
[...]
```

Alltube is not public on my server, btw.

# Steps to reproduce

- install alltube with no public access
- visit alltube url
- examine bookmarklet

# Expected behavior

- neither username nor password should be in the source code of the alltube page
- at least inform user that this link includes the credentials! (if  i bookmark this, the credentials are saved to disk in clear text)

Please, fix as soon as possible!

**Comment by yalh76** [comment]
Tested on last version, no more login and password on the bookmarklet
